[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
image = "0.25.6"
ravif = "0.11.12"
reqwest = "0.12.15"
rusqlite = { version = "0.36.0", features = ["bundled"] }
scraper = "0.23.1"
sysinfo = "0.35.1"
tokio = { version = "~1.45.1", features = ["full"] }
url = "2.5.4"
